### ISSUE TITLE
CI CD failed build

### ISSUE THREAD

**Issue by svf97** [k8-proxy/k8-proxy-documentation#123]
https://github.com/k8-proxy/k8-proxy-documentation/actions
Build fails for CI CD deployment
![image](https://user-images.githubusercontent.com/60857664/117963558-d2afe400-b320-11eb-8f32-eec549c48258.png)

**Comment by samarthdd** [comment]
Bug from base github build
Reference and fixed according to below workaround

https://github.com/ZachJW34/nx-plus/issues/106

**Comment by GINAGC** [comment]
Thank you @samarthdd. @svf97 I see the updates now, so I am closing this one.
